//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basesBC
    {
        public int Id { get; set; }
        public string ORIGEN { get; set; }
        public Nullable<int> AÑO { get; set; }
        public Nullable<int> PERIODO { get; set; }
        public string CUENTACONTABLE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> SALDOINICIALLOCAL { get; set; }
        public Nullable<decimal> DEBITOLOCAL { get; set; }
        public Nullable<decimal> CREDITOLOCAL { get; set; }
        public Nullable<decimal> SALDOFINALLOCAL { get; set; }
        public Nullable<decimal> MOVIMIENTOLOCAL { get; set; }
        public Nullable<decimal> SALDOINICIALDOLAR { get; set; }
        public Nullable<decimal> DEBITODOLAR { get; set; }
        public Nullable<decimal> CREDITODOLAR { get; set; }
        public Nullable<decimal> SALDOFINALDOLAR { get; set; }
        public Nullable<decimal> MOVIMIENTODOLAR { get; set; }
        public string VALIDA { get; set; }
        public string BGPL { get; set; }
        public string USERID_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string USERID_MODIFICACION { get; set; }
        public string ESTADO { get; set; }
    }
}
