//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basesBCHojaTrabajo
    {
        public int ID { get; set; }
        public Nullable<int> AÑO { get; set; }
        public Nullable<int> PERIODO { get; set; }
        public string CUENTA_CONTABLE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> MOVIMIENTO_LOCAL { get; set; }
        public Nullable<decimal> SALDO_FINAL_LOCAL { get; set; }
        public string INFORME_VARIACIONES_BG { get; set; }
        public string INFORME_VARIACIONES_GYP { get; set; }
        public string PL_PACIFICO__CONCEPTO_ { get; set; }
        public string PL_PACIFICO__AGRUPACION_ { get; set; }
        public Nullable<System.DateTime> FECHA_CARGA { get; set; }
    }
}
