//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_Cuentas_Proyectos
    {
        public int ID { get; set; }
        public string Num_Cuenta { get; set; }
        public Nullable<int> ID_Plan { get; set; }
        public Nullable<int> ID_Proyecto { get; set; }
    }
}
