//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAC_Estado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAC_Estado()
        {
            this.DAC_Scripts = new HashSet<DAC_Scripts>();
            this.DAC_ScriptsContinua = new HashSet<DAC_ScriptsContinua>();
            this.DAC_ScriptsContinua1 = new HashSet<DAC_ScriptsContinua>();
            this.DAC_ScriptsContinua2 = new HashSet<DAC_ScriptsContinua>();
            this.DAC_ScriptsContinua3 = new HashSet<DAC_ScriptsContinua>();
        }
    
        public int idEstado { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_Scripts> DAC_Scripts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_ScriptsContinua> DAC_ScriptsContinua { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_ScriptsContinua> DAC_ScriptsContinua1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_ScriptsContinua> DAC_ScriptsContinua2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_ScriptsContinua> DAC_ScriptsContinua3 { get; set; }
    }
}
