//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAC_Scripts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAC_Scripts()
        {
            this.DAC_HistorialCambios = new HashSet<DAC_HistorialCambios>();
            this.DAC_HistorialReportesScript = new HashSet<DAC_HistorialReportesScript>();
        }
    
        public int idScript { get; set; }
        public string nombreScript { get; set; }
        public string codigoScript { get; set; }
        public Nullable<int> idNegocio { get; set; }
        public Nullable<int> fases { get; set; }
        public Nullable<int> idTipScript { get; set; }
        public Nullable<int> idAuditor { get; set; }
        public Nullable<int> idEstados { get; set; }
        public Nullable<int> idProyecto { get; set; }
        public Nullable<int> idEjecScript { get; set; }
        public Nullable<int> idPerEjec { get; set; }
        public Nullable<int> idPeriodoA { get; set; }
    
        public virtual DAC_Ejecucion_Script DAC_Ejecucion_Script { get; set; }
        public virtual DAC_Estado DAC_Estado { get; set; }
        public virtual DAC_Peridiocidad_Ejecucion DAC_Peridiocidad_Ejecucion { get; set; }
        public virtual DAC_Periodo_Analisis DAC_Periodo_Analisis { get; set; }
        public virtual DAC_Tipologia_Script DAC_Tipologia_Script { get; set; }
        public virtual DD_Proyecto DD_Proyecto { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_HistorialCambios> DAC_HistorialCambios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_HistorialReportesScript> DAC_HistorialReportesScript { get; set; }
    }
}
