//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAC_ScriptsContinua
    {
        public int ID { get; set; }
        public string Código_Script { get; set; }
        public Nullable<int> Año { get; set; }
        public string Negocio { get; set; }
        public string Nombre_Script { get; set; }
        public string Script_Abreviado { get; set; }
        public string Descripción_de_Script { get; set; }
        public string Fuente { get; set; }
        public Nullable<int> idTipScript { get; set; }
        public string Gestor_Responsable { get; set; }
        public Nullable<int> idGerenteAdjunto { get; set; }
        public Nullable<int> idAuditor { get; set; }
        public Nullable<int> idAreaAuditada { get; set; }
        public Nullable<int> idContactoAuditado { get; set; }
        public Nullable<int> Fase_1 { get; set; }
        public Nullable<int> Fase_2 { get; set; }
        public Nullable<int> Fase_3 { get; set; }
        public Nullable<int> Fase_4 { get; set; }
        public string Ejecución_de_Script { get; set; }
        public string Cantidad_de_Meses_de_análisis { get; set; }
        public string Ruta { get; set; }
        public string graficaPowerBI { get; set; }
    
        public virtual DAC_Estado DAC_Estado { get; set; }
        public virtual DAC_Estado DAC_Estado1 { get; set; }
        public virtual DAC_Estado DAC_Estado2 { get; set; }
        public virtual DAC_Estado DAC_Estado3 { get; set; }
        public virtual TS_Contacto TS_Contacto { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual DAC_Tipologia_Script DAC_Tipologia_Script { get; set; }
    }
}
