//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAC_HistorialReportesScript
    {
        public int idHistorialReporte { get; set; }
        public Nullable<int> idScript { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string estado { get; set; }
        public string nombreArchivo { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string contentType { get; set; }
        public byte[] data { get; set; }
    
        public virtual DAC_Scripts DAC_Scripts { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
