//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MultiserviciosEntities1 : DbContext
    {
        public MultiserviciosEntities1()
            : base("name=MultiserviciosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TS_Estructura> TS_Estructura { get; set; }
        public virtual DbSet<TD_VacacionesRegistro> TD_VacacionesRegistro { get; set; }
        public virtual DbSet<Usuarios_Objetivos> Usuarios_Objetivos { get; set; }
    
        public virtual ObjectResult<SP_WT_RESULTADO_AUDITORIA_Result> SP_WT_RESULTADO_AUDITORIA(string nEGOCIO, string gERENCIA, Nullable<int> aÑO)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var aÑOParameter = aÑO.HasValue ?
                new ObjectParameter("AÑO", aÑO) :
                new ObjectParameter("AÑO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_RESULTADO_AUDITORIA_Result>("SP_WT_RESULTADO_AUDITORIA", nEGOCIOParameter, gERENCIAParameter, aÑOParameter);
        }
    
        public virtual ObjectResult<SP_WT_SEGUIMIENTO_OBSERVACIONES_Result> SP_WT_SEGUIMIENTO_OBSERVACIONES(string nEGOCIO, string gERENCIA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_SEGUIMIENTO_OBSERVACIONES_Result>("SP_WT_SEGUIMIENTO_OBSERVACIONES", nEGOCIOParameter, gERENCIAParameter);
        }
    
        public virtual ObjectResult<SP_CONTROLES_EVALUADOS_Result1> SP_CONTROLES_EVALUADOS(string nEGOCIO, string gERENCIA, Nullable<int> aÑO)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var aÑOParameter = aÑO.HasValue ?
                new ObjectParameter("AÑO", aÑO) :
                new ObjectParameter("AÑO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONTROLES_EVALUADOS_Result1>("SP_CONTROLES_EVALUADOS", nEGOCIOParameter, gERENCIAParameter, aÑOParameter);
        }
    
        public virtual ObjectResult<SP_WT_SEGUIMIENTO_OBSERVACIONES_2_Result> SP_WT_SEGUIMIENTO_OBSERVACIONES_2(string nEGOCIO, string gERENCIA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_SEGUIMIENTO_OBSERVACIONES_2_Result>("SP_WT_SEGUIMIENTO_OBSERVACIONES_2", nEGOCIOParameter, gERENCIAParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_RESULTADOS_AUDITORIA_1_Result> SP_WT_DETALLE_RESULTADOS_AUDITORIA_1(string nEGOCIO, string gERENCIA, Nullable<int> yEAR)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_RESULTADOS_AUDITORIA_1_Result>("SP_WT_DETALLE_RESULTADOS_AUDITORIA_1", nEGOCIOParameter, gERENCIAParameter, yEARParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_RESULTADOS_AUDITORIA_2_Result> SP_WT_DETALLE_RESULTADOS_AUDITORIA_2(string nEGOCIO, string gERENCIA, Nullable<int> yEAR)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_RESULTADOS_AUDITORIA_2_Result>("SP_WT_DETALLE_RESULTADOS_AUDITORIA_2", nEGOCIOParameter, gERENCIAParameter, yEARParameter);
        }
    
        public virtual ObjectResult<SP_DETALLE_CONTROLES_EVALUADOS_1_Result> SP_DETALLE_CONTROLES_EVALUADOS_1(string nEGOCIO, string gERENCIA, Nullable<int> yEAR)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DETALLE_CONTROLES_EVALUADOS_1_Result>("SP_DETALLE_CONTROLES_EVALUADOS_1", nEGOCIOParameter, gERENCIAParameter, yEARParameter);
        }
    
        public virtual ObjectResult<SP_DETALLE_CONTROLES_EVALUADOS_2_Result> SP_DETALLE_CONTROLES_EVALUADOS_2(string nEGOCIO, string gERENCIA, Nullable<int> yEAR)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DETALLE_CONTROLES_EVALUADOS_2_Result>("SP_DETALLE_CONTROLES_EVALUADOS_2", nEGOCIOParameter, gERENCIAParameter, yEARParameter);
        }
    
        public virtual ObjectResult<SP_DETALLE_CONTROLES_EVALUADOS_3_Result> SP_DETALLE_CONTROLES_EVALUADOS_3(string nEGOCIO, string gERENCIA, Nullable<int> yEAR)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DETALLE_CONTROLES_EVALUADOS_3_Result>("SP_DETALLE_CONTROLES_EVALUADOS_3", nEGOCIOParameter, gERENCIAParameter, yEARParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_1_Result> SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_1(string nEGOCIO, string gERENCIA, Nullable<System.DateTime> fECHA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_1_Result>("SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_1", nEGOCIOParameter, gERENCIAParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_2_Result> SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_2(string nEGOCIO, string gERENCIA, Nullable<System.DateTime> fECHA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_2_Result>("SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_2", nEGOCIOParameter, gERENCIAParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SP_WT_REPORTE_CLAVE_Result> SP_WT_REPORTE_CLAVE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_REPORTE_CLAVE_Result>("SP_WT_REPORTE_CLAVE");
        }
    
        public virtual ObjectResult<SP_WT_REPORTE_GENERAL_Result> SP_WT_REPORTE_GENERAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_REPORTE_GENERAL_Result>("SP_WT_REPORTE_GENERAL");
        }
    
        public virtual ObjectResult<SP_WT_REPORTE_SOX_Result> SP_WT_REPORTE_SOX()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_REPORTE_SOX_Result>("SP_WT_REPORTE_SOX");
        }
    
        public virtual ObjectResult<SP_WT_VACACIONES_CONSOLIDADO_Result> SP_WT_VACACIONES_CONSOLIDADO(Nullable<System.DateTime> fECHA)
        {
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_VACACIONES_CONSOLIDADO_Result>("SP_WT_VACACIONES_CONSOLIDADO", fECHAParameter);
        }
    
        public virtual ObjectResult<SP_WT_GANTT_VACACIONES_Result> SP_WT_GANTT_VACACIONES(Nullable<System.DateTime> dATE)
        {
            var dATEParameter = dATE.HasValue ?
                new ObjectParameter("DATE", dATE) :
                new ObjectParameter("DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_GANTT_VACACIONES_Result>("SP_WT_GANTT_VACACIONES", dATEParameter);
        }
    
        public virtual ObjectResult<SP_VACACIONES_REGISTRO_Result> SP_VACACIONES_REGISTRO(string tIPO, Nullable<int> iD)
        {
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VACACIONES_REGISTRO_Result>("SP_VACACIONES_REGISTRO", tIPOParameter, iDParameter);
        }
    
        public virtual ObjectResult<SP_WT_CONTROL_PERIODO_DIAS_Result> SP_WT_CONTROL_PERIODO_DIAS(Nullable<System.DateTime> fECHA, Nullable<int> iD)
        {
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_CONTROL_PERIODO_DIAS_Result>("SP_WT_CONTROL_PERIODO_DIAS", fECHAParameter, iDParameter);
        }
    
        public virtual ObjectResult<SP_WT_VACACIONES_CONSOLIDADO_DETALLE_Result> SP_WT_VACACIONES_CONSOLIDADO_DETALLE(Nullable<System.DateTime> fECHA, Nullable<int> iD)
        {
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_VACACIONES_CONSOLIDADO_DETALLE_Result>("SP_WT_VACACIONES_CONSOLIDADO_DETALLE", fECHAParameter, iDParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_DISTRIBUCION_EMISOR_2_Result> SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_DISTRIBUCION_EMISOR_2(string nEGOCIO, string gERENCIA, Nullable<System.DateTime> fECHA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_DISTRIBUCION_EMISOR_2_Result>("SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_DISTRIBUCION_EMISOR_2", nEGOCIOParameter, gERENCIAParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_DISTRIBUCION_ESTADO_RIESGO_Result> SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_DISTRIBUCION_ESTADO_RIESGO(string nEGOCIO, string gERENCIA, Nullable<System.DateTime> fECHA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_DISTRIBUCION_ESTADO_RIESGO_Result>("SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_DISTRIBUCION_ESTADO_RIESGO", nEGOCIOParameter, gERENCIAParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_EMISION_Result> SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_EMISION(string nEGOCIO, string gERENCIA, Nullable<System.DateTime> fECHA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_EMISION_Result>("SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_EMISION", nEGOCIOParameter, gERENCIAParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_CRITICIDAD_Result> SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_CRITICIDAD(string nEGOCIO, string gERENCIA, Nullable<System.DateTime> fECHA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_CRITICIDAD_Result>("SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_CRITICIDAD", nEGOCIOParameter, gERENCIAParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_EMISOR_2_Result> SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_EMISOR_2(string nEGOCIO, string gERENCIA, Nullable<System.DateTime> fECHA)
        {
            var nEGOCIOParameter = nEGOCIO != null ?
                new ObjectParameter("NEGOCIO", nEGOCIO) :
                new ObjectParameter("NEGOCIO", typeof(string));
    
            var gERENCIAParameter = gERENCIA != null ?
                new ObjectParameter("GERENCIA", gERENCIA) :
                new ObjectParameter("GERENCIA", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_EMISOR_2_Result>("SP_WT_DETALLE_SEGUIMIENTO_OBSERVACIONES_STOCK_ANTIGUEDAD_EMISOR_2", nEGOCIOParameter, gERENCIAParameter, fECHAParameter);
        }
    
        public virtual ObjectResult<SP_WT_REPORTE_CLAVE1_Result> SP_WT_REPORTE_CLAVE1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_REPORTE_CLAVE1_Result>("SP_WT_REPORTE_CLAVE1");
        }
    
        public virtual ObjectResult<SP_WT_REPORTE_GENERAL1_Result> SP_WT_REPORTE_GENERAL1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_REPORTE_GENERAL1_Result>("SP_WT_REPORTE_GENERAL1");
        }
    
        public virtual ObjectResult<SP_WT_REPORTES_Result1> SP_WT_REPORTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_WT_REPORTES_Result1>("SP_WT_REPORTES");
        }
    }
}
