//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Cambios_Universo
    {
        public int idCambioUniverso { get; set; }
        public Nullable<int> id_Universo { get; set; }
        public string Accion { get; set; }
        public Nullable<int> id_Referencia { get; set; }
        public Nullable<int> id_Usuario { get; set; }
    
        public virtual DD_Universo DD_Universo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
