//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_ProcesoEvaluado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DD_ProcesoEvaluado()
        {
            this.DD_Proyecto = new HashSet<DD_Proyecto>();
        }
    
        public int IdProcesoEvaluado { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdNegocios { get; set; }
        public string MacroPadre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_Proyecto> DD_Proyecto { get; set; }
    }
}
