//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DD_Proyecto()
        {
            this.DAC_Scripts = new HashSet<DAC_Scripts>();
        }
    
        public int IdProyecto { get; set; }
        public Nullable<int> IdPlanAnual { get; set; }
        public Nullable<int> IdInforme { get; set; }
        public string Codigo { get; set; }
        public string Riesgo { get; set; }
        public string Compañia { get; set; }
        public Nullable<int> IdEstadosProyecto { get; set; }
        public string Macroproceso { get; set; }
        public Nullable<int> Plan { get; set; }
        public Nullable<int> IdCanal { get; set; }
        public Nullable<int> IdLineaNegocio { get; set; }
        public Nullable<int> NroInfo_PPS { get; set; }
        public Nullable<int> NroInfo_EPV { get; set; }
        public Nullable<int> NroInfo_EPS { get; set; }
        public Nullable<int> NroInfo_PRE { get; set; }
        public string Evaluación { get; set; }
        public string Tipo { get; set; }
        public string Expectativa { get; set; }
        public Nullable<int> Criticidad { get; set; }
        public Nullable<System.DateTime> FechaInicioPlan { get; set; }
        public Nullable<System.DateTime> FechaFinPlan { get; set; }
        public Nullable<System.DateTime> FechaInicioEjecución { get; set; }
        public Nullable<System.DateTime> FechaFinEjecución { get; set; }
        public Nullable<int> DíasProyecto { get; set; }
        public Nullable<int> DíasExtra { get; set; }
        public Nullable<int> DíasEjecución { get; set; }
        public Nullable<System.DateTime> FechaEnvío { get; set; }
        public string Enviadopor { get; set; }
        public Nullable<int> PAC { get; set; }
        public string CAI { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaBloqueo { get; set; }
        public string Auditor_1 { get; set; }
        public string Auditor_2 { get; set; }
        public string Auditor_3 { get; set; }
        public string Auditor_4 { get; set; }
        public string Auditor_5 { get; set; }
        public string Responsable_s_ { get; set; }
        public string Supervisor_es_ { get; set; }
        public string Subgerente_s_ { get; set; }
        public string Gerente { get; set; }
        public Nullable<System.DateTime> FechaEmisión { get; set; }
        public Nullable<int> Anexo30 { get; set; }
        public Nullable<int> IdProcesoEvaluado { get; set; }
        public Nullable<int> IdRiesgoDelTrabajo { get; set; }
        public Nullable<int> IdRiesgoInherente { get; set; }
        public Nullable<int> IdAdministraciónDelRiesgo { get; set; }
        public Nullable<System.DateTime> FechaCOA { get; set; }
        public Nullable<System.DateTime> FechaLimiteRegulador { get; set; }
        public Nullable<System.DateTime> FechaEnvioRegulador { get; set; }
        public Nullable<int> ProyectoSIEMBRA { get; set; }
        public Nullable<int> CantidadSprint { get; set; }
        public Nullable<int> IDEvaluacion_Plan { get; set; }
        public Nullable<int> IDRiesgoBCP { get; set; }
        public Nullable<System.DateTime> FechaReemplazo { get; set; }
        public Nullable<int> IdProyectoReemplazo { get; set; }
        public Nullable<int> Cant_Pruebas_analiticas_plan { get; set; }
        public Nullable<int> Cant_Pruebas_analiticas_real { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_Scripts> DAC_Scripts { get; set; }
        public virtual DD_Informe DD_Informe { get; set; }
        public virtual DD_PlanAnual DD_PlanAnual { get; set; }
        public virtual DD_ProcesoEvaluado DD_ProcesoEvaluado { get; set; }
        public virtual DD_Proyecto DD_Proyecto1 { get; set; }
        public virtual DD_Proyecto DD_Proyecto2 { get; set; }
        public virtual DPA_Evaluacion_Plan DPA_Evaluacion_Plan { get; set; }
    }
}
