//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_Universo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DD_Universo()
        {
            this.DD_Cambios_Universo = new HashSet<DD_Cambios_Universo>();
        }
    
        public int idUniverso { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> idNegocio { get; set; }
        public string Equipo { get; set; }
        public string Riesgo { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual DD_Informe DD_Informe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_Cambios_Universo> DD_Cambios_Universo { get; set; }
    }
}
