//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Criterio_Scoring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DPA_Criterio_Scoring()
        {
            this.DPA_Scoring_Evaluacion = new HashSet<DPA_Scoring_Evaluacion>();
        }
    
        public int ID_Criterio_Scoring { get; set; }
        public string Criterio { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<int> Anio_Plan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Scoring_Evaluacion> DPA_Scoring_Evaluacion { get; set; }
    }
}
