//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Log_Evaluacion
    {
        public int ID_Log { get; set; }
        public int ID_Usuario { get; set; }
        public Nullable<int> ID_Evaluacion { get; set; }
        public string Evaluacion { get; set; }
        public string Nuevo_Nombre { get; set; }
        public int ID_Negocio { get; set; }
        public int ID_Tipo_Operacion { get; set; }
        public string Detalle_Operacion { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
