//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Criterio_Votacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DPA_Criterio_Votacion()
        {
            this.DPA_Opcion_Votacion = new HashSet<DPA_Opcion_Votacion>();
        }
    
        public int ID_Criterio { get; set; }
        public string Criterio { get; set; }
        public Nullable<decimal> Peso_Criterio { get; set; }
        public Nullable<int> ID_Plan_Anual { get; set; }
        public Nullable<int> Flag_Referencial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Opcion_Votacion> DPA_Opcion_Votacion { get; set; }
    }
}
