//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Evaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DPA_Evaluacion()
        {
            this.DPA_Evaluacion_Plan = new HashSet<DPA_Evaluacion_Plan>();
        }
    
        public int ID_Evaluacion { get; set; }
        public string Evaluacion { get; set; }
        public int ID_Negocio { get; set; }
        public Nullable<int> ID_Proceso_Evaluado { get; set; }
        public string Objetivo { get; set; }
        public string Centro_Costo { get; set; }
        public string Atributo_Universo { get; set; }
        public string Tipo_Evaluacion { get; set; }
        public Nullable<int> ID_Equipo_Responsable { get; set; }
        public string PAC { get; set; }
        public string Anexo_30 { get; set; }
        public string Regulatorio { get; set; }
        public string N_SBS { get; set; }
        public string Evaluacion_SBS { get; set; }
        public string SOX { get; set; }
        public string Fase_SOX { get; set; }
        public string Nombre_Mesa { get; set; }
        public string Comentario { get; set; }
        public string Squad_COE_Area { get; set; }
        public string Aplicaciones { get; set; }
        public string RPA { get; set; }
        public string Chatbot { get; set; }
        public string IA { get; set; }
        public string API { get; set; }
        public Nullable<int> N_Riesgos { get; set; }
        public Nullable<int> N_Controles { get; set; }
        public string Accesos_Aplicacion { get; set; }
        public string Accesos_BD { get; set; }
        public Nullable<decimal> Ratio_Dias_Control { get; set; }
        public string Uso_Analitica_EWP { get; set; }
        public string Uso_Analitica_Registrado { get; set; }
        public string Analítica_Tipo_Pruebas { get; set; }
        public string SIEMBRA { get; set; }
        public string SIEGA { get; set; }
        public string RIEGA { get; set; }
    
        public virtual DPA_Equipo DPA_Equipo { get; set; }
        public virtual DPA_Negocio DPA_Negocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Evaluacion_Plan> DPA_Evaluacion_Plan { get; set; }
    }
}
