//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Scoring_Evaluacion
    {
        public int ID_Scoring_Evaluacion { get; set; }
        public int ID_Criterio_Scoring { get; set; }
        public int Scoring { get; set; }
        public int ID_Evaluacion_Plan { get; set; }
    
        public virtual DPA_Criterio_Scoring DPA_Criterio_Scoring { get; set; }
        public virtual DPA_Evaluacion_Plan DPA_Evaluacion_Plan { get; set; }
    }
}
