//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Auditor_Tiempo_Extra
    {
        public int ID_Auditor_Tiempo_Extra { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Tipo_Tiempo_Extra { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual DPA_Tipo_Tiempo_Extra DPA_Tipo_Tiempo_Extra { get; set; }
    }
}
