//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Opcion_Votacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DPA_Opcion_Votacion()
        {
            this.DPA_Votacion = new HashSet<DPA_Votacion>();
        }
    
        public int ID_Opcion_Votacion { get; set; }
        public string Opcion { get; set; }
        public decimal Peso_Opcion { get; set; }
        public int ID_Criterio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Votacion> DPA_Votacion { get; set; }
        public virtual DPA_Criterio_Votacion DPA_Criterio_Votacion { get; set; }
    }
}
