//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Log_Evaluacion_Plan
    {
        public int ID_Log { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Evaluacion_Plan { get; set; }
        public int ID_Tipo_Operacion { get; set; }
        public string Detalle_Operacion { get; set; }
        public Nullable<int> ID_Referencia { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual DPA_Evaluacion_Plan DPA_Evaluacion_Plan { get; set; }
    }
}
