//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Votacion
    {
        public int ID_Votacion { get; set; }
        public int ID_Evaluacion_Plan { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Opcion_Votacion { get; set; }
    
        public virtual DPA_Opcion_Votacion DPA_Opcion_Votacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual DPA_Evaluacion_Plan DPA_Evaluacion_Plan { get; set; }
    }
}
