//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPA_Evaluacion_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DPA_Evaluacion_Plan()
        {
            this.DPA_Auditor_Evaluacion = new HashSet<DPA_Auditor_Evaluacion>();
            this.DPA_Log_Evaluacion_Plan = new HashSet<DPA_Log_Evaluacion_Plan>();
            this.DPA_Scoring_Evaluacion = new HashSet<DPA_Scoring_Evaluacion>();
            this.DPA_Votacion = new HashSet<DPA_Votacion>();
            this.DD_Proyecto = new HashSet<DD_Proyecto>();
        }
    
        public int ID_Evaluacion_Plan { get; set; }
        public int ID_Evaluacion { get; set; }
        public int ID_Plan_Anual { get; set; }
        public Nullable<int> ID_Riesgo_Asociado { get; set; }
        public string Ultimo_Calificativo { get; set; }
        public string Criticidad_Elegida { get; set; }
        public Nullable<int> Dias_Ajustado { get; set; }
        public Nullable<int> N_Aud_Ajustado { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public string Programado { get; set; }
        public string Codigo_Proyecto { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Auditor_Evaluacion> DPA_Auditor_Evaluacion { get; set; }
        public virtual DPA_Evaluacion DPA_Evaluacion { get; set; }
        public virtual DPA_Plan_Anual DPA_Plan_Anual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Log_Evaluacion_Plan> DPA_Log_Evaluacion_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Scoring_Evaluacion> DPA_Scoring_Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Votacion> DPA_Votacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_Proyecto> DD_Proyecto { get; set; }
    }
}
