//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Usuario = new HashSet<Usuario>();
            this.DAC_Scripts = new HashSet<DAC_Scripts>();
            this.DAC_HistorialCambios = new HashSet<DAC_HistorialCambios>();
            this.DAC_HistorialReportesScript = new HashSet<DAC_HistorialReportesScript>();
            this.DAC_ScriptsContinua = new HashSet<DAC_ScriptsContinua>();
            this.DAC_ScriptsContinua1 = new HashSet<DAC_ScriptsContinua>();
            this.Rotacion = new HashSet<Rotacion>();
        }
    
        public int IdPersona { get; set; }
        public int IdCompañia { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Dni { get; set; }
        public Nullable<int> Activo { get; set; }
        public string Función { get; set; }
        public string Matrícula { get; set; }
        public string SubGerencia { get; set; }
        public string Equipo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string NombreSharepoint { get; set; }
        public Nullable<byte> Administrador { get; set; }
        public string NombreTC { get; set; }
        public string NombreSharepoint2 { get; set; }
        public string NombreSharepoint3 { get; set; }
        public string NombreSharepoint4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_Scripts> DAC_Scripts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_HistorialCambios> DAC_HistorialCambios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_HistorialReportesScript> DAC_HistorialReportesScript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_ScriptsContinua> DAC_ScriptsContinua { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAC_ScriptsContinua> DAC_ScriptsContinua1 { get; set; }
        public virtual Compañia Compañia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rotacion> Rotacion { get; set; }
    }
}
