//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R1_DupNAB_
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FECDOCOTR { get; set; }
        public string CODMONEDA { get; set; }
        public Nullable<double> MTODOCINGLOCAL { get; set; }
        public string NUMREFDOCAUX { get; set; }
        public Nullable<double> AÑOCORTE { get; set; }
        public Nullable<double> MESCORTE { get; set; }
        public string TIPODOCING { get; set; }
        public string CODENTFINANING { get; set; }
        public string DESCENTFINAN { get; set; }
        public string CODAGENCIA { get; set; }
        public string TIPOOFIBCP { get; set; }
        public string NOMOFIBCP { get; set; }
        public Nullable<double> MTODOCINGMONEDA { get; set; }
        public Nullable<double> TIPOCAMBIO { get; set; }
        public string DESCCTAENTFINAN { get; set; }
        public string NUMCTAENTFINAN { get; set; }
        public Nullable<System.DateTime> FECING { get; set; }
        public string STSRELING { get; set; }
        public Nullable<double> NUMRELING { get; set; }
        public string CODCAJA { get; set; }
        public string DESCCAJA { get; set; }
        public string CODCAJERO { get; set; }
        public string STSDOCING { get; set; }
        public string INDCONCIL { get; set; }
        public string OBSRELING { get; set; }
        public string OBSERVACION { get; set; }
        public string NOMBRE_TERCERO { get; set; }
        public string TIPO { get; set; }
        public Nullable<double> NUMRELCTA { get; set; }
        public string CODTARJCRED { get; set; }
        public Nullable<System.DateTime> FECVALDOCING { get; set; }
        public string DIROFIBCP { get; set; }
        public string AUX { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Detalle { get; set; }
    }
}
