//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rotacion
    {
        public int IdRotacion { get; set; }
        public int IdPersona { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string Función { get; set; }
        public string Cargo { get; set; }
        public string Matrícula { get; set; }
        public string SubGerencia { get; set; }
        public string Equipo { get; set; }
        public string Planilla { get; set; }
        public Nullable<int> IdJefeDirecto { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
