//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    
    public partial class SP_CONTROLES_EVALUADOS_Result1
    {
        public string Efectividad { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
