//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    
    public partial class SP_WT_REPORTES_Result1
    {
        public int IdReporte { get; set; }
        public string Nombre { get; set; }
        public string Enlace { get; set; }
        public string IMG { get; set; }
        public string Descripcion { get; set; }
    }
}
