//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_VacacionesRegistro
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Descripción { get; set; }
        public Nullable<int> Ajuste { get; set; }
        public Nullable<int> Ejecutado { get; set; }
    }
}
