//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Ampliación
    {
        public int ID { get; set; }
        public string ID_Observación { get; set; }
        public string Motivo { get; set; }
        public string Nuevo_Plan { get; set; }
        public Nullable<System.DateTime> Fecha_Propuesta { get; set; }
        public int ID_Aprobador { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
    }
}
