//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Estructura_Seguimiento_Historial
    {
        public int ID_Estructura_Seguimiento_Historial { get; set; }
        public string Unidad_Responsable { get; set; }
        public string Accion { get; set; }
        public string Campo { get; set; }
        public string Campo_Before { get; set; }
        public string Campo_After { get; set; }
        public System.DateTime Fecha_Cambio { get; set; }
        public string Usuario { get; set; }
    }
}
