//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Observacion_Cambio
    {
        public int ID { get; set; }
        public int Identificador { get; set; }
        public string ID_OBSERVACION { get; set; }
        public Nullable<int> ID_UNIDAD_RESPONSABLE { get; set; }
        public string TITULO_OBSERVACION { get; set; }
        public string EMISOR { get; set; }
        public Nullable<int> AÑO { get; set; }
        public string NEGOCIO { get; set; }
        public string INFORME { get; set; }
        public string BANMEDICA { get; set; }
        public string ENVIADO_EXT { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIADO { get; set; }
        public string INFRACCIÓN { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
    }
}
