//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Proyecto
    {
        public int IdProyecto { get; set; }
        public Nullable<int> IdPlanAnual { get; set; }
        public Nullable<int> IdInforme { get; set; }
        public string Codigo { get; set; }
        public string Riesgo { get; set; }
        public string Compañia { get; set; }
        public Nullable<int> IdEstadosProyecto { get; set; }
        public string Macroproceso { get; set; }
        public Nullable<int> Plan { get; set; }
        public string Evaluación { get; set; }
        public string Tipo { get; set; }
        public string Criticidad { get; set; }
        public Nullable<System.DateTime> FechaInicioPlan { get; set; }
        public Nullable<System.DateTime> FechaFinPlan { get; set; }
        public Nullable<System.DateTime> FechaInicioEjecución { get; set; }
        public Nullable<System.DateTime> FechaFinEjecución { get; set; }
        public Nullable<int> DíasProyecto { get; set; }
        public Nullable<int> DíasEjecución { get; set; }
        public Nullable<System.DateTime> FechaEnvío { get; set; }
        public string Enviadopor { get; set; }
        public Nullable<int> PAC { get; set; }
        public Nullable<int> Anexo30 { get; set; }
        public string CAI { get; set; }
        public string Cuatrimestral { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaBloqueo { get; set; }
        public string Auditor_1_plan { get; set; }
        public string Auditor_2_plan { get; set; }
        public string Auditor_3_plan { get; set; }
        public string Auditor_4_plan { get; set; }
        public string Auditor_5_plan { get; set; }
        public string Supervisor_plan { get; set; }
        public string Subgerente_plan { get; set; }
        public string Auditor_1_ejecucion { get; set; }
        public string Auditor_2_ejecucion { get; set; }
        public string Auditor_3_ejecucion { get; set; }
        public string Auditor_4_ejecucion { get; set; }
        public string Auditor_5_ejecucion { get; set; }
        public string Supervisor_ejecucion { get; set; }
        public string Subgerente_ejecucion { get; set; }
        public string Gerente { get; set; }
        public Nullable<System.DateTime> FechaEmisión { get; set; }
        public Nullable<int> IdProcesoEvaluado { get; set; }
        public Nullable<int> IdRiesgoDelTrabajo { get; set; }
        public Nullable<int> IdRiesgoInherente { get; set; }
        public Nullable<int> IDRiesgoBCP { get; set; }
        public Nullable<int> IdAdministraciónDelRiesgo { get; set; }
        public Nullable<System.DateTime> FechaCOA { get; set; }
        public Nullable<int> CantidadSprint { get; set; }
        public Nullable<int> IDEvaluacion_Plan { get; set; }
        public Nullable<System.DateTime> FechaReemplazo { get; set; }
        public Nullable<int> IdProyectoReemplazo { get; set; }
        public Nullable<int> Cant_Pruebas_analiticas_plan { get; set; }
        public Nullable<int> Cant_Pruebas_analiticas_real { get; set; }
        public Nullable<int> PlanAnual_flag { get; set; }
        public Nullable<int> Criticidad_num { get; set; }
        public Nullable<int> MapaAseguramiento { get; set; }
        public Nullable<int> Controles_Auto_plan { get; set; }
        public Nullable<System.DateTime> FechaInicioAprobada { get; set; }
    }
}
