//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Persona
    {
        public int Identificador { get; set; }
        public int IdPersona { get; set; }
        public int IdCompañia { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Dni { get; set; }
        public Nullable<int> Activo { get; set; }
        public string Función { get; set; }
        public string Matrícula { get; set; }
        public string SubGerencia { get; set; }
        public string Equipo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string NombreSharepoint { get; set; }
        public Nullable<byte> Administrador { get; set; }
        public string NombreTC { get; set; }
        public string NombreSharepoint2 { get; set; }
        public string NombreSharepoint3 { get; set; }
        public string NombreSharepoint4 { get; set; }
    }
}
