//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_Proyecto_Riesgo_Control
    {
        public int IdProyecto_Riesgo_Control { get; set; }
        public string Referencia_del_proceso { get; set; }
        public string NroRiesgo { get; set; }
        public string NroControl { get; set; }
        public Nullable<int> C1eraLinea { get; set; }
        public Nullable<int> C2daLinea { get; set; }
        public Nullable<int> C3eraLinea { get; set; }
        public Nullable<int> Riesgo_1eraLinea { get; set; }
        public Nullable<int> Riesgo_2daLinea { get; set; }
        public Nullable<int> Control_1eraLinea { get; set; }
        public Nullable<int> Control_2daLinea { get; set; }
    }
}
