//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TG_RiesgoBCP
    {
        public int IDTipo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IDTipoBCP { get; set; }
    }
}
