//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_User
    {
        public int ID { get; set; }
        public string TMGUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string StaffNumber { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Title { get; set; }
        public Nullable<int> OldRID { get; set; }
        public int ActiveStatusLID { get; set; }
        public string SecurityToken { get; set; }
        public string LMG { get; set; }
        public System.DateTime LMD { get; set; }
        public string LMU { get; set; }
        public string StatusMessage { get; set; }
        public byte IsSystem { get; set; }
    }
}
