//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Estructura
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int ID_Padre { get; set; }
        public string GERENCIA_NIVEL_0 { get; set; }
        public string GERENCIA_NIVEL_1 { get; set; }
        public string GERENCIA_NIVEL_2 { get; set; }
        public string GERENCIA_NIVEL_3 { get; set; }
        public string GERENCIA_NIVEL_4 { get; set; }
        public string GERENCIA_NIVEL_5 { get; set; }
    }
}
