//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Unidad_Responsable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TS_Unidad_Responsable()
        {
            this.TS_Unidad_Responsable_Contacto = new HashSet<TS_Unidad_Responsable_Contacto>();
            this.TS_Unidad_Responsable_Referencia = new HashSet<TS_Unidad_Responsable_Referencia>();
        }
    
        public int ID { get; set; }
        public int ID_Padre { get; set; }
        public string Nombre { get; set; }
        public int Nivel { get; set; }
        public int flagActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Unidad_Responsable_Contacto> TS_Unidad_Responsable_Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Unidad_Responsable_Referencia> TS_Unidad_Responsable_Referencia { get; set; }
    }
}
