//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Unidad_Responsable_Contacto
    {
        public int ID_Unidad_Responsable { get; set; }
        public int ID_Contacto { get; set; }
        public int ID_Rol { get; set; }
    
        public virtual TS_Contacto TS_Contacto { get; set; }
        public virtual TS_Rol TS_Rol { get; set; }
        public virtual TS_Unidad_Responsable TS_Unidad_Responsable { get; set; }
    }
}
