//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.UsuarioModuloRol = new HashSet<UsuarioModuloRol>();
            this.DD_Cambios_Universo = new HashSet<DD_Cambios_Universo>();
            this.Usuario_Log = new HashSet<Usuario_Log>();
            this.DPA_Votacion = new HashSet<DPA_Votacion>();
            this.DPA_Auditor_Evaluacion = new HashSet<DPA_Auditor_Evaluacion>();
            this.DPA_Auditor_Tiempo_Extra = new HashSet<DPA_Auditor_Tiempo_Extra>();
            this.DPA_Log_Evaluacion_Plan = new HashSet<DPA_Log_Evaluacion_Plan>();
        }
    
        public int IdUsuario { get; set; }
        public int IdPersona { get; set; }
        public string Usuario1 { get; set; }
        public string Contraseña { get; set; }
        public string token_recovery { get; set; }
    
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioModuloRol> UsuarioModuloRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DD_Cambios_Universo> DD_Cambios_Universo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Log> Usuario_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Votacion> DPA_Votacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Auditor_Evaluacion> DPA_Auditor_Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Auditor_Tiempo_Extra> DPA_Auditor_Tiempo_Extra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPA_Log_Evaluacion_Plan> DPA_Log_Evaluacion_Plan { get; set; }
    }
}
