//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Log
    {
        public int ID_Operacion { get; set; }
        public int ID_Usuario { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
