//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_Objetivos
    {
        public int ID { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public string Estado { get; set; }
        public string Nombre_Ape { get; set; }
        public string Función { get; set; }
        public string Matrícula { get; set; }
        public string SubGerencia { get; set; }
        public string Equipo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string NombreSharepoint { get; set; }
        public Nullable<int> IDJefeDirecto { get; set; }
        public string DNI { get; set; }
        public Nullable<byte> Administrador { get; set; }
        public string NombreTC { get; set; }
        public string NombreSharepoint2 { get; set; }
        public string NombreSharepoint3 { get; set; }
        public string NombreSharepoint4 { get; set; }
    }
}
