//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BC_Cuentas_Proyectos
    {
        public int ID { get; set; }
        public string Cuenta_Contable { get; set; }
        public string DESCRIPCION { get; set; }
        public string Plan_Anual { get; set; }
        public string Macroproceso { get; set; }
        public string Evaluación { get; set; }
        public string Cod_Proyecto { get; set; }
    }
}
