//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_ADMINISTRACION_USUARIOS
    {
        public int IdUsuario { get; set; }
        public string Persona { get; set; }
        public int IdModulo { get; set; }
        public int IdRol { get; set; }
    }
}
