//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BC_Hojas_Cargadas
    {
        public int ID { get; set; }
        public Nullable<int> AÑO { get; set; }
        public Nullable<int> PERIODO { get; set; }
        public Nullable<System.DateTime> FECHA_CARGA { get; set; }
    }
}
