//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DAC_Vista_List_Scripts
    {
        public int ID { get; set; }
        public string Código_Script { get; set; }
        public Nullable<int> Año { get; set; }
        public string Nombre_Script { get; set; }
        public string Descripción_de_Script { get; set; }
        public string Gestor { get; set; }
        public Nullable<int> IdGA { get; set; }
        public string Gerente_Adjunto { get; set; }
        public Nullable<int> IdAud { get; set; }
        public string Auditor { get; set; }
        public string Monitoreo { get; set; }
        public Nullable<int> Fase_1 { get; set; }
        public Nullable<int> Fase_2 { get; set; }
        public Nullable<int> Fase_3 { get; set; }
        public Nullable<int> Fase_4 { get; set; }
        public string Estado { get; set; }
        public string Ruta { get; set; }
        public string graficaPowerBI { get; set; }
    }
}
