//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AU_Persona_Usuario_Rotacion
    {
        public int IdPersona { get; set; }
        public int IdCompañia { get; set; }
        public int IdUsuario { get; set; }
        public int IdRotacion { get; set; }
        public Nullable<int> IdJefeDirecto { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Dni { get; set; }
        public string Función { get; set; }
        public string Matrícula { get; set; }
        public string SubGerencia { get; set; }
        public string Equipo { get; set; }
        public string NombreSharepoint { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string Cargo { get; set; }
        public string Planilla { get; set; }
        public Nullable<int> Activo { get; set; }
    }
}
